### ISSUE TITLE
Commandline arguments for syncjob add parsed correctly?

### ISSUE THREAD

**Issue by atom83** [derJD/python-mailcow#1]
Hello,

Are the commandline arguments for the "syncjob add" parsed correctly from API?
See below the arguments.

Shoudn't there be something like: user1, passwort1? or how can I define creds for source mailbox? and target mailbox should be "--username" and not "--parameters".

was mache ich da falsch?

thanks

mfg
Thomas

```

mailcow syncjob add --help
usage: mailcow syncjob add [-h] [--parameters PARAMETERS] [--host1 HOST1]
                           [--port1 PORT1] [--password PASSWORD] [--enc1 ENC1]
                           [--mins_internal MINS_INTERNAL]
                           [--subfolder2 SUBFOLDER2] [--maxage MAXAGE]
                           [--maxbytespersecond MAXBYTESPERSECOND]
                           [--timeout1 TIMEOUT1] [--timeout2 TIMEOUT2]
                           [--exclude EXCLUDE] [--custom_params CUSTOM_PARAMS]
                           [--delete2duplicates] [--delete1] [--delete2]
                           [--automap] [--skipcrossduplicates]
                           [--subscribeall] [--active]

optional arguments:
  -h, --help            show this help message and exit
  --parameters PARAMETERS
                        your local mailcow mailbox
  --host1 HOST1         the smtp server where mails should be synced from
  --port1 PORT1         the smtp port of the target mail server
  --password PASSWORD   the password of the mailbox
  --enc1 ENC1           the encryption method used to connect to the
                        mailserver
  --mins_internal MINS_INTERNAL
                        the interval in which messages should be syned
  --subfolder2 SUBFOLDER2
                        sync into subfolder on destination (empty = do not use
                        subfolder)
  --maxage MAXAGE       only sync messages up to this age in days
  --maxbytespersecond MAXBYTESPERSECOND
                        max speed transfer limit for the sync
  --timeout1 TIMEOUT1   timeout for connection to remote host
  --timeout2 TIMEOUT2   timeout for connection to local host
  --exclude EXCLUDE     exclude objects (regex)
  --custom_params CUSTOM_PARAMS
                        custom parameters
  --delete2duplicates, --no-delete2duplicates
                        delete duplicates on destination (--delete2duplicates)
  --delete1, --no-delete1
                        delete from source when completed (--delete1)
  --delete2, --no-delete2
                        delete messages on destination that are not on source
                        (--delete2)
  --automap, --no-automap
                        try to automap folders ("Sent items", "Sent" => "Sent"
                        etc.) (--automap)
  --skipcrossduplicates, --no-skipcrossduplicates
                        skip duplicate messages across folders (first come,
                        first serve) (--skipcrossduplicates)
  --subscribeall, --no-subscribeall
                        subscribe all folders (--subscribeall)
  --active, --no-active
                        enables or disables the sync job


```

**Comment by derJD** [comment]
Hi @atom83,

Thanks for using python-mailcow and submitting this issue.

Neither you did something wrong nor this tool. In fact the examples provided by the API don't add up with the parameters it is providing.
You can take a look at the examples [here](https://demo.mailcow.email/api/#/Sync%20jobs/Create%20sync%20job)

You're right. According to the examples there should be "username" instead of "parameters".

Rather than implementing a workaround in this tool, this should be fixed in the upstream mailcow-dockerized repo.
[These](https://github.com/mailcow/mailcow-dockerized/blob/89a00f6d24eab13b1a8ff3b39335eba81666c974/data/web/api/openapi.yaml#L1397-L1456) lines
are all the parameters provided for "add/syncjob" and therefore displayed/used/parsed by python-mailcow.
As soon as this gets fixed upstream and you update your mailcow instance, python-mailcow will display/use the new/fixed arguments,
without touching a single line of code here =).

I suggest you grab [these upstream lines](https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/api/openapi.yaml#L1397-L1456) and add everything
you need. Kudos from the mailcow maintainers will await you for that =).
If you are totally uncomfortable with editing that yaml file, I can do that for you as I'm already familiar with that. But only as a last resort ;).

Cheers,
derJD

**Comment by atom83** [comment]
Thanks, Issue posted in mailcow repo. and I will try to fix that locally for my instance.

Thanks
